name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui
        
      - name: Restore dependencies
        run: dotnet restore --force
        working-directory: MauiApp1\ManagementSystem
        
      - name: Build
        run: dotnet build -c Release -f net8.0-windows10.0.19041.0
        working-directory: MauiApp1\ManagementSystem

      - name: Publish
        run: dotnet publish -c Release -f net8.0-windows10.0.19041.0
        working-directory: MauiApp1\ManagementSystem
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          name: Build
          path: MauiApp1\bin\MauiApp1\ManagementSystem\bin\Release\net8.0-windows10.0.19041.0\win10-arm64\*.* # Adjust the file pattern as needed
